<?php require_once('common/header.phtml'); ?>
<div id="main">
    <div class="inner">
        <header>
                <h1>Knowledge and Tradition.</h1>
                <p>This is what we value. We use the medium of technology - but that's all it is - a medium.
                    When you work with us, you'll notice that in all our brands these values are the core building blocks.</p>
        </header>

        <h2>Our Businesses</h2>
        <ul class="alt brands">
            <li class="brand-vesica">
                <a href="#" class="logo title">Vesica <span class="color-pink">Heritage and Library Collections</span></a>
                <br />
                Vesica Heritage and Library Collections collects and preserves antique objects, books and manuscripts from around
                the Islamic world. It's part of our vision to preserve and eventually make this knowledge available to those who
                can put it to better use.
            </li>

            <li class="brand-in">
                <a href="https://islamic.network/" target="_blank" class="logo title tq">Islamic <span class="color-tq">Network</span></a>
                <br />
                Islamic Network is a network of free digital Islamic services. From prayer times calculations to hosted Quran
                and Masjid apps and websites, the Islamic Network makes technology and the web accessible for the Islamic world.
            </li>

            <li class="brand-fw">
                <a href="https://futuwwa.co.uk" target="_blank" class="logo title green">Futuwwa <span class="color-green">Publishing</span></a>
                <br />
                Futuwwa Publishing is a London, UK based publisher of history, philosophy and 
                language books from the Islamic World.
            </li>

            <li class="brand-vesica">
                <a href="#" class="logo title blue">Docker <span class="color-blue">Stack</span> Deploy</a>
                <br />
                A consulting business and website based around Production ready Docker Swarm implementations.
            </li>


        </ul>
    </div>
</div>
                    
<?php require_once('common/footer.phtml'); ?>
