connections:
    database:
        doctrine:
            host: mysql
            username: dev
            password: dev
            dbname: database
            port: 3306
            mode: dev # dev or prod
            driver: pdo_mysql
    memcache:
        host: memcached
        port: 11211

slim:
    settings:
        display_error_details: true # use for debugging only
        add_content_length: true # Adds content length header to all responses 
